/*
Code generated by Carto Workflows Engine (RUN)
- workflowid:7a956830-4c17-417f-902e-c31a29229920
- versionid:fa18c1a7514caea4
- paramsid:97d170e1550eee4a
*/

/*==================== native.h3polyfill (v1) [6913b1c7-8282-4049-81af-4ba17ee94a79]  ====================*/
BEGIN
CREATE TABLE IF NOT EXISTS `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_1372a306e980c44a_result`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(
    CURRENT_TIMESTAMP(), INTERVAL 30 DAY
  )
)
AS
  WITH __h3 AS
  (
    SELECT
    `carto-un.carto`.H3_POLYFILL_MODE(
        geom,
        7,
        'center'
      ) h3s
    FROM
      (
        SELECT *
        FROM `cartobq.docs.CHI_boundary`
        WHERE geom IS NOT NULL
      ) s
  )
  SELECT DISTINCT h3
  FROM __h3, __h3.h3s AS h3;
END;

/*==================== native.readquery (v1) [1707a4e1-652f-4cd3-a1a4-bc727d7b9ed2]  ====================*/
BEGIN
CREATE VIEW IF NOT EXISTS `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_54c5514e43b8373a_out`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(
    CURRENT_TIMESTAMP(), INTERVAL 30 DAY
  )
)
AS
  SELECT do_data.*, do_geom.geom
    FROM `carto-data.ac_lqe3zwgu.sub_usa_acs_demographics_sociodemographics_usa_blockgroup_2015_5yrs_20072011` do_data
    INNER JOIN `carto-data.ac_lqe3zwgu.sub_carto_geography_usa_blockgroup_2015` do_geom ON do_data.geoid=do_geom.geoid;
END;

/*==================== native.readquery (v1) [3f49e8a3-7bf3-4246-b791-39c5f955fee5]  ====================*/
BEGIN
CREATE VIEW IF NOT EXISTS `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_92e8134e75e9d1ab_out`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(
    CURRENT_TIMESTAMP(), INTERVAL 30 DAY
  )
)
AS
  SELECT do_data.*, do_geom.geom
    FROM `carto-data.ac_lqe3zwgu.sub_usa_acs_demographics_sociodemographics_usa_blockgroup_2015_5yrs_20112015` do_data
    INNER JOIN `carto-data.ac_lqe3zwgu.sub_carto_geography_usa_blockgroup_2015` do_geom ON do_data.geoid=do_geom.geoid;
END;

/*==================== native.readquery (v1) [98006a2a-a48e-47ef-8719-e05bb8a79f5e]  ====================*/
BEGIN
CREATE VIEW IF NOT EXISTS `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_1d8b7df4a8a99880_out`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(
    CURRENT_TIMESTAMP(), INTERVAL 30 DAY
  )
)
AS
  SELECT do_data.*, do_geom.geom
    FROM `carto-data.ac_lqe3zwgu.sub_usa_acs_demographics_sociodemographics_usa_blockgroup_2015_5yrs_20142018` do_data
    INNER JOIN `carto-data.ac_lqe3zwgu.sub_carto_geography_usa_blockgroup_2015` do_geom ON do_data.geoid=do_geom.geoid;
END;

/*==================== native.readquery (v1) [408ac770-cf19-4606-8145-3b42935e17e2]  ====================*/
BEGIN
CREATE VIEW IF NOT EXISTS `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_0e5a35fa39cc5386_out`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(
    CURRENT_TIMESTAMP(), INTERVAL 30 DAY
  )
)
AS
  SELECT do_data.*, do_geom.geom
    FROM `carto-data.ac_lqe3zwgu.sub_usa_acs_demographics_sociodemographics_usa_blockgroup_2019_yearly_2019` do_data
    INNER JOIN `carto-data.ac_lqe3zwgu.sub_usa_tiger_geography_usa_blockgroup_2019` do_geom ON do_data.geoid=do_geom.geoid;
END;

/*==================== native.readquery (v1) [dd1847f8-1257-4c5a-9ed3-70629f52b947]  ====================*/
BEGIN
CREATE VIEW IF NOT EXISTS `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_7ca52621af754634_out`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(
    CURRENT_TIMESTAMP(), INTERVAL 30 DAY
  )
)
AS
  SELECT do_data.*, do_geom.geom
    FROM `carto-data.ac_lqe3zwgu.sub_usa_acs_demographics_sociodemographics_usa_blockgroup_2019_yearly_2020` do_data
    INNER JOIN `carto-data.ac_lqe3zwgu.sub_usa_tiger_geography_usa_blockgroup_2019` do_geom ON do_data.geoid=do_geom.geoid;
END;

/*==================== native.readquery (v1) [55733446-0e1d-41e3-b738-ff7d52f16cb8]  ====================*/
BEGIN
CREATE VIEW IF NOT EXISTS `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_9fa33fe70383b08a_out`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(
    CURRENT_TIMESTAMP(), INTERVAL 30 DAY
  )
)
AS
  SELECT do_data.*, do_geom.geom
    FROM `carto-data.ac_lqe3zwgu.sub_usa_acs_demographics_sociodemographics_usa_blockgroup_2015_5yrs_20122016` do_data
    INNER JOIN `carto-data.ac_lqe3zwgu.sub_carto_geography_usa_blockgroup_2015` do_geom ON do_data.geoid=do_geom.geoid;
END;

/*==================== native.readquery (v1) [01d66959-bad3-47a8-9a79-42f130a218a8]  ====================*/
BEGIN
CREATE VIEW IF NOT EXISTS `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_7d073e3bd722c518_out`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(
    CURRENT_TIMESTAMP(), INTERVAL 30 DAY
  )
)
AS
  SELECT do_data.*, do_geom.geom
    FROM `carto-data.ac_lqe3zwgu.sub_usa_acs_demographics_sociodemographics_usa_blockgroup_2015_5yrs_20102014` do_data
    INNER JOIN `carto-data.ac_lqe3zwgu.sub_carto_geography_usa_blockgroup_2015` do_geom ON do_data.geoid=do_geom.geoid;
END;

/*==================== native.readquery (v1) [e7a3f18a-02d6-47fb-9ad4-5af795ea8305]  ====================*/
BEGIN
CREATE VIEW IF NOT EXISTS `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_96811d7489a33958_out`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(
    CURRENT_TIMESTAMP(), INTERVAL 30 DAY
  )
)
AS
  SELECT do_data.*, do_geom.geom
    FROM `carto-data.ac_lqe3zwgu.sub_usa_acs_demographics_sociodemographics_usa_blockgroup_2015_5yrs_20092013` do_data
    INNER JOIN `carto-data.ac_lqe3zwgu.sub_carto_geography_usa_blockgroup_2015` do_geom ON do_data.geoid=do_geom.geoid;
END;

/*==================== native.readquery (v1) [0afac149-923d-4929-91c8-cb791f3f6863]  ====================*/
BEGIN
CREATE VIEW IF NOT EXISTS `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_11b450fcf1c649c4_out`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(
    CURRENT_TIMESTAMP(), INTERVAL 30 DAY
  )
)
AS
  SELECT do_data.*, do_geom.geom
    FROM `carto-data.ac_lqe3zwgu.sub_usa_acs_demographics_sociodemographics_usa_zcta5_2015_5yrs_20082012` do_data
    INNER JOIN `carto-data.ac_lqe3zwgu.sub_carto_geography_usa_zcta5_2015` do_geom ON do_data.geoid=do_geom.geoid;
END;

/*==================== native.readquery (v1) [0097804e-c3bc-496a-8a88-f87a0b02bbdf]  ====================*/
BEGIN
CREATE VIEW IF NOT EXISTS `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_d6cff7df4343f774_out`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(
    CURRENT_TIMESTAMP(), INTERVAL 30 DAY
  )
)
AS
  SELECT do_data.*, do_geom.geom
    FROM `carto-data.ac_lqe3zwgu.sub_usa_acs_demographics_sociodemographics_usa_blockgroup_2015_5yrs_20062010` do_data
    INNER JOIN `carto-data.ac_lqe3zwgu.sub_carto_geography_usa_blockgroup_2015` do_geom ON do_data.geoid=do_geom.geoid;
END;

/*==================== native.readquery (v1) [f17b6091-56ad-4506-8d24-042ba1d9b5f5]  ====================*/
BEGIN
CREATE VIEW IF NOT EXISTS `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_0d4af29d9fa055e8_out`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(
    CURRENT_TIMESTAMP(), INTERVAL 30 DAY
  )
)
AS
  SELECT geoid AS h3, * EXCEPT(geoid) FROM `carto-data.ac_lqe3zwgu.sub_carto_derived_spatialfeatures_usa_h3res8_v1_yearly_v3`;
END;

/*==================== native.readquery (v1) [987ebc73-85ca-46e9-b2c0-c99d8714c638]  ====================*/
BEGIN
CREATE VIEW IF NOT EXISTS `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_6458c10f14869080_out`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(
    CURRENT_TIMESTAMP(), INTERVAL 30 DAY
  )
)
AS
  SELECT do_data.*, do_geom.geom
    FROM `carto-data.ac_lqe3zwgu.sub_usa_acs_demographics_sociodemographics_usa_blockgroup_2015_5yrs_20132017` do_data
    INNER JOIN `carto-data.ac_lqe3zwgu.sub_carto_geography_usa_blockgroup_2015` do_geom ON do_data.geoid=do_geom.geoid;
END;

/*==================== native.select (v1) [3ea355e0-f52e-49d7-b530-0c5a781122af]  ====================*/
BEGIN
CREATE TABLE IF NOT EXISTS `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_276eb2aa0c0be079_result`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(
    CURRENT_TIMESTAMP(), INTERVAL 30 DAY
  )
)
AS
  SELECT geom, geoid, do_date,
  total_pop,
  median_age,
  median_rent,
  black_pop,
  hispanic_pop,
  owner_occupied_housing_units_median_value,
  vacant_housing_units,
  housing_units,
  families_with_young_children
              FROM `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_54c5514e43b8373a_out`;
END;

/*==================== native.select (v1) [3ea355e0-f52e-49d7-b530-0c5a781122af-1725442413200]  ====================*/
BEGIN
CREATE TABLE IF NOT EXISTS `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_2e9014e82fe19db8_result`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(
    CURRENT_TIMESTAMP(), INTERVAL 30 DAY
  )
)
AS
  SELECT geom, geoid, do_date,
  total_pop,
  median_age,
  median_rent,
  black_pop,
  hispanic_pop,
  owner_occupied_housing_units_median_value,
  vacant_housing_units,
  housing_units,
  families_with_young_children
              FROM `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_92e8134e75e9d1ab_out`;
END;

/*==================== native.select (v1) [3ea355e0-f52e-49d7-b530-0c5a781122af-1725442413200-1725442415754]  ====================*/
BEGIN
CREATE TABLE IF NOT EXISTS `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_f694bba1969cab4e_result`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(
    CURRENT_TIMESTAMP(), INTERVAL 30 DAY
  )
)
AS
  SELECT geom, geoid, do_date,
  total_pop,
  median_age,
  median_rent,
  black_pop,
  hispanic_pop,
  owner_occupied_housing_units_median_value,
  vacant_housing_units,
  housing_units,
  families_with_young_children
              FROM `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_1d8b7df4a8a99880_out`;
END;

/*==================== native.select (v1) [3ea355e0-f52e-49d7-b530-0c5a781122af-1725442413200-1725442415754-1727261781190]  ====================*/
BEGIN
CREATE TABLE IF NOT EXISTS `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_947e6bba75e55462_result`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(
    CURRENT_TIMESTAMP(), INTERVAL 30 DAY
  )
)
AS
  SELECT geom, geoid, do_date,
  total_pop,
  median_age,
  median_rent,
  black_pop,
  hispanic_pop,
  owner_occupied_housing_units_median_value,
  vacant_housing_units,
  housing_units,
  families_with_young_children
              FROM `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_0e5a35fa39cc5386_out`;
END;

/*==================== native.select (v1) [3ea355e0-f52e-49d7-b530-0c5a781122af-1725442413200-1725442415754-1727261781190-1727261785982]  ====================*/
BEGIN
CREATE TABLE IF NOT EXISTS `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_eaa5b099cb81ec12_result`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(
    CURRENT_TIMESTAMP(), INTERVAL 30 DAY
  )
)
AS
  SELECT geom, geoid, do_date,
  total_pop,
  median_age,
  median_rent,
  black_pop,
  hispanic_pop,
  owner_occupied_housing_units_median_value,
  vacant_housing_units,
  housing_units,
  families_with_young_children
              FROM `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_7ca52621af754634_out`;
END;

/*==================== native.select (v1) [3ea355e0-f52e-49d7-b530-0c5a781122af-1725442413200-1727260560670-1727260833291]  ====================*/
BEGIN
CREATE TABLE IF NOT EXISTS `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_0fb0dc1e2573b875_result`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(
    CURRENT_TIMESTAMP(), INTERVAL 30 DAY
  )
)
AS
  SELECT geom, geoid, do_date,
  total_pop,
  median_age,
  median_rent,
  black_pop,
  hispanic_pop,
  owner_occupied_housing_units_median_value,
  vacant_housing_units,
  housing_units,
  families_with_young_children
              FROM `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_9fa33fe70383b08a_out`;
END;

/*==================== native.select (v1) [3ea355e0-f52e-49d7-b530-0c5a781122af-1727261737509-1727261749500]  ====================*/
BEGIN
CREATE TABLE IF NOT EXISTS `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_d92a9783d1e7ce4e_result`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(
    CURRENT_TIMESTAMP(), INTERVAL 30 DAY
  )
)
AS
  SELECT geom, geoid, do_date,
  total_pop,
  median_age,
  median_rent,
  black_pop,
  hispanic_pop,
  owner_occupied_housing_units_median_value,
  vacant_housing_units,
  housing_units,
  families_with_young_children
              FROM `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_7d073e3bd722c518_out`;
END;

/*==================== native.select (v1) [3ea355e0-f52e-49d7-b530-0c5a781122af-1727261737509-1727261744115]  ====================*/
BEGIN
CREATE TABLE IF NOT EXISTS `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_9154dec49cbb42e2_result`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(
    CURRENT_TIMESTAMP(), INTERVAL 30 DAY
  )
)
AS
  SELECT geom, geoid, do_date,
  total_pop,
  median_age,
  median_rent,
  black_pop,
  hispanic_pop,
  owner_occupied_housing_units_median_value,
  vacant_housing_units,
  housing_units,
  families_with_young_children
              FROM `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_96811d7489a33958_out`;
END;

/*==================== native.select (v1) [3ea355e0-f52e-49d7-b530-0c5a781122af-1727261737509]  ====================*/
BEGIN
CREATE TABLE IF NOT EXISTS `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_28ad301c26275c2e_result`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(
    CURRENT_TIMESTAMP(), INTERVAL 30 DAY
  )
)
AS
  SELECT geom, geoid, do_date,
  total_pop,
  median_age,
  median_rent,
  black_pop,
  hispanic_pop,
  owner_occupied_housing_units_median_value,
  vacant_housing_units,
  housing_units,
  families_with_young_children
              FROM `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_11b450fcf1c649c4_out`;
END;

/*==================== native.select (v1) [3ea355e0-f52e-49d7-b530-0c5a781122af-1727261827321]  ====================*/
BEGIN
CREATE TABLE IF NOT EXISTS `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_1fe0c48ce5671fe3_result`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(
    CURRENT_TIMESTAMP(), INTERVAL 30 DAY
  )
)
AS
  SELECT geom, geoid, do_date,
  total_pop,
  median_age,
  median_rent,
  black_pop,
  hispanic_pop,
  owner_occupied_housing_units_median_value,
  vacant_housing_units,
  housing_units,
  families_with_young_children
              FROM `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_d6cff7df4343f774_out`;
END;

/*==================== native.select (v1) [5c74ef74-5342-49ab-812d-7270ab1d0783]  ====================*/
BEGIN
CREATE TABLE IF NOT EXISTS `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_23a9efda0ee5b354_result`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(
    CURRENT_TIMESTAMP(), INTERVAL 30 DAY
  )
)
AS
  SELECT h3, urbanity
  FROM `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_0d4af29d9fa055e8_out`;
END;

/*==================== native.select (v1) [3ea355e0-f52e-49d7-b530-0c5a781122af-1725442413200-1727260560670]  ====================*/
BEGIN
CREATE TABLE IF NOT EXISTS `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_5ec92f0643cdd666_result`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(
    CURRENT_TIMESTAMP(), INTERVAL 30 DAY
  )
)
AS
  SELECT geom, geoid, do_date,
  total_pop,
  median_age,
  median_rent,
  black_pop,
  hispanic_pop,
  owner_occupied_housing_units_median_value,
  vacant_housing_units,
  housing_units,
  families_with_young_children
              FROM `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_6458c10f14869080_out`;
END;

/*==================== native.h3enrich (v1) [17255adb-eb78-4fa7-9c71-a79e4a9a5e97]  ====================*/
BEGIN
BEGIN
  DECLARE tablesCount INT64;
  DECLARE tableNames ARRAY<STRING> DEFAULT ['\'WORKFLOW_7325e013be685ea0_ec7caa950443c8b9_result\''];
  EXECUTE IMMEDIATE '''
    SELECT COUNT(1) AS cnt
    FROM `cartodb-on-gcp-datascience.workflows_temp.__TABLES_SUMMARY__`
    WHERE table_id IN (''' || ARRAY_TO_STRING(tableNames, ', ') || ''')
  ''' INTO tablesCount;
  IF tablesCount < 1 THEN
    BEGIN
      BEGIN
      DECLARE tempInputTable STRING DEFAULT 'cartodb-on-gcp-datascience.workflows_temp.' || REPLACE(GENERATE_UUID(), '-', '_');
      DECLARE tempOutputTable STRING DEFAULT 'cartodb-on-gcp-datascience.workflows_temp.' || REPLACE(GENERATE_UUID(), '-', '_');
      DECLARE tempOutputTableKring STRING DEFAULT 'cartodb-on-gcp-datascience.workflows_temp.' || REPLACE(GENERATE_UUID(), '-', '_');
      DECLARE tempOutputTableKringRenamed STRING DEFAULT 'cartodb-on-gcp-datascience.workflows_temp.' || REPLACE(GENERATE_UUID(), '-', '_');
      EXECUTE IMMEDIATE
      REPLACE(
        '''CREATE TABLE IF NOT EXISTS `##tablename##`
        OPTIONS (
          expiration_timestamp = TIMESTAMP_ADD(
            CURRENT_TIMESTAMP(), INTERVAL 30 DAY
          )
        )
        AS
          SELECT * FROM `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_1372a306e980c44a_result`''',
        '##tablename##',
        tempInputTable
      );
      CALL `carto-un.carto`.ENRICH_GRID(
        'h3',
        tempInputTable,
        'h3',
        'SELECT * FROM `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_276eb2aa0c0be079_result`',
        'geom',
        [('total_pop', 'sum'), ('median_age', 'avg'), ('median_rent', 'avg'), ('black_pop', 'sum'), ('hispanic_pop', 'sum'), ('owner_occupied_housing_units_median_value', 'sum'), ('vacant_housing_units', 'sum'), ('housing_units', 'sum'), ('families_with_young_children', 'sum')],
        [tempOutputTable]
      );
      
      EXECUTE IMMEDIATE
      REPLACE(
        '''CREATE TABLE IF NOT EXISTS `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_ec7caa950443c8b9_result`
        OPTIONS (
          expiration_timestamp = TIMESTAMP_ADD(
            CURRENT_TIMESTAMP(), INTERVAL 30 DAY
          )
        )
        AS
          SELECT * FROM `##tablename##`''',
        '##tablename##',
        tempOutputTable
      );
      END;
    END;
  END IF;
END;
END;

/*==================== native.selectexpression (v1) [9d2ad7db-240a-40bc-a286-3f0bcfadcd64-1725444838451]  ====================*/
BEGIN
CREATE TABLE IF NOT EXISTS `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_ccddd72e7cd672a6_result`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(
    CURRENT_TIMESTAMP(), INTERVAL 30 DAY
  )
)
AS
  SELECT *,
    2007 AS acs_year
  FROM `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_ec7caa950443c8b9_result`;
END;

/*==================== native.h3enrich (v1) [17255adb-eb78-4fa7-9c71-a79e4a9a5e97-1725443583320]  ====================*/
BEGIN
BEGIN
  DECLARE tablesCount INT64;
  DECLARE tableNames ARRAY<STRING> DEFAULT ['\'WORKFLOW_7325e013be685ea0_c63d6fe379d0a2b4_result\''];
  EXECUTE IMMEDIATE '''
    SELECT COUNT(1) AS cnt
    FROM `cartodb-on-gcp-datascience.workflows_temp.__TABLES_SUMMARY__`
    WHERE table_id IN (''' || ARRAY_TO_STRING(tableNames, ', ') || ''')
  ''' INTO tablesCount;
  IF tablesCount < 1 THEN
    BEGIN
      BEGIN
      DECLARE tempInputTable STRING DEFAULT 'cartodb-on-gcp-datascience.workflows_temp.' || REPLACE(GENERATE_UUID(), '-', '_');
      DECLARE tempOutputTable STRING DEFAULT 'cartodb-on-gcp-datascience.workflows_temp.' || REPLACE(GENERATE_UUID(), '-', '_');
      DECLARE tempOutputTableKring STRING DEFAULT 'cartodb-on-gcp-datascience.workflows_temp.' || REPLACE(GENERATE_UUID(), '-', '_');
      DECLARE tempOutputTableKringRenamed STRING DEFAULT 'cartodb-on-gcp-datascience.workflows_temp.' || REPLACE(GENERATE_UUID(), '-', '_');
      EXECUTE IMMEDIATE
      REPLACE(
        '''CREATE TABLE IF NOT EXISTS `##tablename##`
        OPTIONS (
          expiration_timestamp = TIMESTAMP_ADD(
            CURRENT_TIMESTAMP(), INTERVAL 30 DAY
          )
        )
        AS
          SELECT * FROM `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_1372a306e980c44a_result`''',
        '##tablename##',
        tempInputTable
      );
      CALL `carto-un.carto`.ENRICH_GRID(
        'h3',
        tempInputTable,
        'h3',
        'SELECT * FROM `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_2e9014e82fe19db8_result`',
        'geom',
        [('total_pop', 'sum'), ('median_age', 'avg'), ('median_rent', 'avg'), ('black_pop', 'sum'), ('hispanic_pop', 'sum'), ('owner_occupied_housing_units_median_value', 'sum'), ('vacant_housing_units', 'sum'), ('housing_units', 'sum'), ('families_with_young_children', 'sum')],
        [tempOutputTable]
      );
      
      EXECUTE IMMEDIATE
      REPLACE(
        '''CREATE TABLE IF NOT EXISTS `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_c63d6fe379d0a2b4_result`
        OPTIONS (
          expiration_timestamp = TIMESTAMP_ADD(
            CURRENT_TIMESTAMP(), INTERVAL 30 DAY
          )
        )
        AS
          SELECT * FROM `##tablename##`''',
        '##tablename##',
        tempOutputTable
      );
      END;
    END;
  END IF;
END;
END;

/*==================== native.h3enrich (v1) [17255adb-eb78-4fa7-9c71-a79e4a9a5e97-1725443583320-1725443612635]  ====================*/
BEGIN
BEGIN
  DECLARE tablesCount INT64;
  DECLARE tableNames ARRAY<STRING> DEFAULT ['\'WORKFLOW_7325e013be685ea0_693de2260df94333_result\''];
  EXECUTE IMMEDIATE '''
    SELECT COUNT(1) AS cnt
    FROM `cartodb-on-gcp-datascience.workflows_temp.__TABLES_SUMMARY__`
    WHERE table_id IN (''' || ARRAY_TO_STRING(tableNames, ', ') || ''')
  ''' INTO tablesCount;
  IF tablesCount < 1 THEN
    BEGIN
      BEGIN
      DECLARE tempInputTable STRING DEFAULT 'cartodb-on-gcp-datascience.workflows_temp.' || REPLACE(GENERATE_UUID(), '-', '_');
      DECLARE tempOutputTable STRING DEFAULT 'cartodb-on-gcp-datascience.workflows_temp.' || REPLACE(GENERATE_UUID(), '-', '_');
      DECLARE tempOutputTableKring STRING DEFAULT 'cartodb-on-gcp-datascience.workflows_temp.' || REPLACE(GENERATE_UUID(), '-', '_');
      DECLARE tempOutputTableKringRenamed STRING DEFAULT 'cartodb-on-gcp-datascience.workflows_temp.' || REPLACE(GENERATE_UUID(), '-', '_');
      EXECUTE IMMEDIATE
      REPLACE(
        '''CREATE TABLE IF NOT EXISTS `##tablename##`
        OPTIONS (
          expiration_timestamp = TIMESTAMP_ADD(
            CURRENT_TIMESTAMP(), INTERVAL 30 DAY
          )
        )
        AS
          SELECT * FROM `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_1372a306e980c44a_result`''',
        '##tablename##',
        tempInputTable
      );
      CALL `carto-un.carto`.ENRICH_GRID(
        'h3',
        tempInputTable,
        'h3',
        'SELECT * FROM `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_f694bba1969cab4e_result`',
        'geom',
        [('total_pop', 'sum'), ('median_age', 'avg'), ('median_rent', 'avg'), ('black_pop', 'sum'), ('hispanic_pop', 'sum'), ('owner_occupied_housing_units_median_value', 'sum'), ('vacant_housing_units', 'sum'), ('housing_units', 'sum'), ('families_with_young_children', 'sum')],
        [tempOutputTable]
      );
      
      EXECUTE IMMEDIATE
      REPLACE(
        '''CREATE TABLE IF NOT EXISTS `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_693de2260df94333_result`
        OPTIONS (
          expiration_timestamp = TIMESTAMP_ADD(
            CURRENT_TIMESTAMP(), INTERVAL 30 DAY
          )
        )
        AS
          SELECT * FROM `##tablename##`''',
        '##tablename##',
        tempOutputTable
      );
      END;
    END;
  END IF;
END;
END;

/*==================== native.h3enrich (v1) [17255adb-eb78-4fa7-9c71-a79e4a9a5e97-1725443583320-1725443612635-1725443632025]  ====================*/
BEGIN
BEGIN
  DECLARE tablesCount INT64;
  DECLARE tableNames ARRAY<STRING> DEFAULT ['\'WORKFLOW_7325e013be685ea0_3fa687a333388193_result\''];
  EXECUTE IMMEDIATE '''
    SELECT COUNT(1) AS cnt
    FROM `cartodb-on-gcp-datascience.workflows_temp.__TABLES_SUMMARY__`
    WHERE table_id IN (''' || ARRAY_TO_STRING(tableNames, ', ') || ''')
  ''' INTO tablesCount;
  IF tablesCount < 1 THEN
    BEGIN
      BEGIN
      DECLARE tempInputTable STRING DEFAULT 'cartodb-on-gcp-datascience.workflows_temp.' || REPLACE(GENERATE_UUID(), '-', '_');
      DECLARE tempOutputTable STRING DEFAULT 'cartodb-on-gcp-datascience.workflows_temp.' || REPLACE(GENERATE_UUID(), '-', '_');
      DECLARE tempOutputTableKring STRING DEFAULT 'cartodb-on-gcp-datascience.workflows_temp.' || REPLACE(GENERATE_UUID(), '-', '_');
      DECLARE tempOutputTableKringRenamed STRING DEFAULT 'cartodb-on-gcp-datascience.workflows_temp.' || REPLACE(GENERATE_UUID(), '-', '_');
      EXECUTE IMMEDIATE
      REPLACE(
        '''CREATE TABLE IF NOT EXISTS `##tablename##`
        OPTIONS (
          expiration_timestamp = TIMESTAMP_ADD(
            CURRENT_TIMESTAMP(), INTERVAL 30 DAY
          )
        )
        AS
          SELECT * FROM `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_1372a306e980c44a_result`''',
        '##tablename##',
        tempInputTable
      );
      CALL `carto-un.carto`.ENRICH_GRID(
        'h3',
        tempInputTable,
        'h3',
        'SELECT * FROM `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_947e6bba75e55462_result`',
        'geom',
        [('total_pop', 'sum'), ('median_age', 'avg'), ('median_rent', 'avg'), ('black_pop', 'sum'), ('hispanic_pop', 'sum'), ('owner_occupied_housing_units_median_value', 'sum'), ('vacant_housing_units', 'sum'), ('housing_units', 'sum'), ('families_with_young_children', 'sum')],
        [tempOutputTable]
      );
      
      EXECUTE IMMEDIATE
      REPLACE(
        '''CREATE TABLE IF NOT EXISTS `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_3fa687a333388193_result`
        OPTIONS (
          expiration_timestamp = TIMESTAMP_ADD(
            CURRENT_TIMESTAMP(), INTERVAL 30 DAY
          )
        )
        AS
          SELECT * FROM `##tablename##`''',
        '##tablename##',
        tempOutputTable
      );
      END;
    END;
  END IF;
END;
END;

/*==================== native.h3enrich (v1) [17255adb-eb78-4fa7-9c71-a79e4a9a5e97-1725443583320-1725443612635-1725443632025-1725443638471]  ====================*/
BEGIN
BEGIN
  DECLARE tablesCount INT64;
  DECLARE tableNames ARRAY<STRING> DEFAULT ['\'WORKFLOW_7325e013be685ea0_e1d810b6744d3f65_result\''];
  EXECUTE IMMEDIATE '''
    SELECT COUNT(1) AS cnt
    FROM `cartodb-on-gcp-datascience.workflows_temp.__TABLES_SUMMARY__`
    WHERE table_id IN (''' || ARRAY_TO_STRING(tableNames, ', ') || ''')
  ''' INTO tablesCount;
  IF tablesCount < 1 THEN
    BEGIN
      BEGIN
      DECLARE tempInputTable STRING DEFAULT 'cartodb-on-gcp-datascience.workflows_temp.' || REPLACE(GENERATE_UUID(), '-', '_');
      DECLARE tempOutputTable STRING DEFAULT 'cartodb-on-gcp-datascience.workflows_temp.' || REPLACE(GENERATE_UUID(), '-', '_');
      DECLARE tempOutputTableKring STRING DEFAULT 'cartodb-on-gcp-datascience.workflows_temp.' || REPLACE(GENERATE_UUID(), '-', '_');
      DECLARE tempOutputTableKringRenamed STRING DEFAULT 'cartodb-on-gcp-datascience.workflows_temp.' || REPLACE(GENERATE_UUID(), '-', '_');
      EXECUTE IMMEDIATE
      REPLACE(
        '''CREATE TABLE IF NOT EXISTS `##tablename##`
        OPTIONS (
          expiration_timestamp = TIMESTAMP_ADD(
            CURRENT_TIMESTAMP(), INTERVAL 30 DAY
          )
        )
        AS
          SELECT * FROM `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_1372a306e980c44a_result`''',
        '##tablename##',
        tempInputTable
      );
      CALL `carto-un.carto`.ENRICH_GRID(
        'h3',
        tempInputTable,
        'h3',
        'SELECT * FROM `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_eaa5b099cb81ec12_result`',
        'geom',
        [('total_pop', 'sum'), ('median_age', 'avg'), ('median_rent', 'avg'), ('black_pop', 'sum'), ('hispanic_pop', 'sum'), ('owner_occupied_housing_units_median_value', 'sum'), ('vacant_housing_units', 'sum'), ('housing_units', 'sum'), ('families_with_young_children', 'sum')],
        [tempOutputTable]
      );
      
      EXECUTE IMMEDIATE
      REPLACE(
        '''CREATE TABLE IF NOT EXISTS `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_e1d810b6744d3f65_result`
        OPTIONS (
          expiration_timestamp = TIMESTAMP_ADD(
            CURRENT_TIMESTAMP(), INTERVAL 30 DAY
          )
        )
        AS
          SELECT * FROM `##tablename##`''',
        '##tablename##',
        tempOutputTable
      );
      END;
    END;
  END IF;
END;
END;

/*==================== native.h3enrich (v1) [17255adb-eb78-4fa7-9c71-a79e4a9a5e97-1727261840962-1727261852244-1727261861613-1727261873285-1727261890926]  ====================*/
BEGIN
BEGIN
  DECLARE tablesCount INT64;
  DECLARE tableNames ARRAY<STRING> DEFAULT ['\'WORKFLOW_7325e013be685ea0_a94a659360aa72b0_result\''];
  EXECUTE IMMEDIATE '''
    SELECT COUNT(1) AS cnt
    FROM `cartodb-on-gcp-datascience.workflows_temp.__TABLES_SUMMARY__`
    WHERE table_id IN (''' || ARRAY_TO_STRING(tableNames, ', ') || ''')
  ''' INTO tablesCount;
  IF tablesCount < 1 THEN
    BEGIN
      BEGIN
      DECLARE tempInputTable STRING DEFAULT 'cartodb-on-gcp-datascience.workflows_temp.' || REPLACE(GENERATE_UUID(), '-', '_');
      DECLARE tempOutputTable STRING DEFAULT 'cartodb-on-gcp-datascience.workflows_temp.' || REPLACE(GENERATE_UUID(), '-', '_');
      DECLARE tempOutputTableKring STRING DEFAULT 'cartodb-on-gcp-datascience.workflows_temp.' || REPLACE(GENERATE_UUID(), '-', '_');
      DECLARE tempOutputTableKringRenamed STRING DEFAULT 'cartodb-on-gcp-datascience.workflows_temp.' || REPLACE(GENERATE_UUID(), '-', '_');
      EXECUTE IMMEDIATE
      REPLACE(
        '''CREATE TABLE IF NOT EXISTS `##tablename##`
        OPTIONS (
          expiration_timestamp = TIMESTAMP_ADD(
            CURRENT_TIMESTAMP(), INTERVAL 30 DAY
          )
        )
        AS
          SELECT * FROM `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_1372a306e980c44a_result`''',
        '##tablename##',
        tempInputTable
      );
      CALL `carto-un.carto`.ENRICH_GRID(
        'h3',
        tempInputTable,
        'h3',
        'SELECT * FROM `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_0fb0dc1e2573b875_result`',
        'geom',
        [('total_pop', 'sum'), ('median_age', 'avg'), ('median_rent', 'avg'), ('black_pop', 'sum'), ('hispanic_pop', 'sum'), ('owner_occupied_housing_units_median_value', 'sum'), ('vacant_housing_units', 'sum'), ('housing_units', 'sum'), ('families_with_young_children', 'sum')],
        [tempOutputTable]
      );
      
      EXECUTE IMMEDIATE
      REPLACE(
        '''CREATE TABLE IF NOT EXISTS `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_a94a659360aa72b0_result`
        OPTIONS (
          expiration_timestamp = TIMESTAMP_ADD(
            CURRENT_TIMESTAMP(), INTERVAL 30 DAY
          )
        )
        AS
          SELECT * FROM `##tablename##`''',
        '##tablename##',
        tempOutputTable
      );
      END;
    END;
  END IF;
END;
END;

/*==================== native.h3enrich (v1) [17255adb-eb78-4fa7-9c71-a79e4a9a5e97-1727261840962-1727261852244-1727261861613-1727261873285]  ====================*/
BEGIN
BEGIN
  DECLARE tablesCount INT64;
  DECLARE tableNames ARRAY<STRING> DEFAULT ['\'WORKFLOW_7325e013be685ea0_23ae261785684c83_result\''];
  EXECUTE IMMEDIATE '''
    SELECT COUNT(1) AS cnt
    FROM `cartodb-on-gcp-datascience.workflows_temp.__TABLES_SUMMARY__`
    WHERE table_id IN (''' || ARRAY_TO_STRING(tableNames, ', ') || ''')
  ''' INTO tablesCount;
  IF tablesCount < 1 THEN
    BEGIN
      BEGIN
      DECLARE tempInputTable STRING DEFAULT 'cartodb-on-gcp-datascience.workflows_temp.' || REPLACE(GENERATE_UUID(), '-', '_');
      DECLARE tempOutputTable STRING DEFAULT 'cartodb-on-gcp-datascience.workflows_temp.' || REPLACE(GENERATE_UUID(), '-', '_');
      DECLARE tempOutputTableKring STRING DEFAULT 'cartodb-on-gcp-datascience.workflows_temp.' || REPLACE(GENERATE_UUID(), '-', '_');
      DECLARE tempOutputTableKringRenamed STRING DEFAULT 'cartodb-on-gcp-datascience.workflows_temp.' || REPLACE(GENERATE_UUID(), '-', '_');
      EXECUTE IMMEDIATE
      REPLACE(
        '''CREATE TABLE IF NOT EXISTS `##tablename##`
        OPTIONS (
          expiration_timestamp = TIMESTAMP_ADD(
            CURRENT_TIMESTAMP(), INTERVAL 30 DAY
          )
        )
        AS
          SELECT * FROM `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_1372a306e980c44a_result`''',
        '##tablename##',
        tempInputTable
      );
      CALL `carto-un.carto`.ENRICH_GRID(
        'h3',
        tempInputTable,
        'h3',
        'SELECT * FROM `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_d92a9783d1e7ce4e_result`',
        'geom',
        [('total_pop', 'sum'), ('median_age', 'avg'), ('median_rent', 'avg'), ('black_pop', 'sum'), ('hispanic_pop', 'sum'), ('owner_occupied_housing_units_median_value', 'sum'), ('vacant_housing_units', 'sum'), ('housing_units', 'sum'), ('families_with_young_children', 'sum')],
        [tempOutputTable]
      );
      
      EXECUTE IMMEDIATE
      REPLACE(
        '''CREATE TABLE IF NOT EXISTS `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_23ae261785684c83_result`
        OPTIONS (
          expiration_timestamp = TIMESTAMP_ADD(
            CURRENT_TIMESTAMP(), INTERVAL 30 DAY
          )
        )
        AS
          SELECT * FROM `##tablename##`''',
        '##tablename##',
        tempOutputTable
      );
      END;
    END;
  END IF;
END;
END;

/*==================== native.h3enrich (v1) [17255adb-eb78-4fa7-9c71-a79e4a9a5e97-1727261840962-1727261852244-1727261861613]  ====================*/
BEGIN
BEGIN
  DECLARE tablesCount INT64;
  DECLARE tableNames ARRAY<STRING> DEFAULT ['\'WORKFLOW_7325e013be685ea0_25e5d77258529f9b_result\''];
  EXECUTE IMMEDIATE '''
    SELECT COUNT(1) AS cnt
    FROM `cartodb-on-gcp-datascience.workflows_temp.__TABLES_SUMMARY__`
    WHERE table_id IN (''' || ARRAY_TO_STRING(tableNames, ', ') || ''')
  ''' INTO tablesCount;
  IF tablesCount < 1 THEN
    BEGIN
      BEGIN
      DECLARE tempInputTable STRING DEFAULT 'cartodb-on-gcp-datascience.workflows_temp.' || REPLACE(GENERATE_UUID(), '-', '_');
      DECLARE tempOutputTable STRING DEFAULT 'cartodb-on-gcp-datascience.workflows_temp.' || REPLACE(GENERATE_UUID(), '-', '_');
      DECLARE tempOutputTableKring STRING DEFAULT 'cartodb-on-gcp-datascience.workflows_temp.' || REPLACE(GENERATE_UUID(), '-', '_');
      DECLARE tempOutputTableKringRenamed STRING DEFAULT 'cartodb-on-gcp-datascience.workflows_temp.' || REPLACE(GENERATE_UUID(), '-', '_');
      EXECUTE IMMEDIATE
      REPLACE(
        '''CREATE TABLE IF NOT EXISTS `##tablename##`
        OPTIONS (
          expiration_timestamp = TIMESTAMP_ADD(
            CURRENT_TIMESTAMP(), INTERVAL 30 DAY
          )
        )
        AS
          SELECT * FROM `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_1372a306e980c44a_result`''',
        '##tablename##',
        tempInputTable
      );
      CALL `carto-un.carto`.ENRICH_GRID(
        'h3',
        tempInputTable,
        'h3',
        'SELECT * FROM `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_9154dec49cbb42e2_result`',
        'geom',
        [('total_pop', 'sum'), ('median_age', 'avg'), ('median_rent', 'avg'), ('black_pop', 'sum'), ('hispanic_pop', 'sum'), ('owner_occupied_housing_units_median_value', 'sum'), ('vacant_housing_units', 'sum'), ('housing_units', 'sum'), ('families_with_young_children', 'sum')],
        [tempOutputTable]
      );
      
      EXECUTE IMMEDIATE
      REPLACE(
        '''CREATE TABLE IF NOT EXISTS `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_25e5d77258529f9b_result`
        OPTIONS (
          expiration_timestamp = TIMESTAMP_ADD(
            CURRENT_TIMESTAMP(), INTERVAL 30 DAY
          )
        )
        AS
          SELECT * FROM `##tablename##`''',
        '##tablename##',
        tempOutputTable
      );
      END;
    END;
  END IF;
END;
END;

/*==================== native.h3enrich (v1) [17255adb-eb78-4fa7-9c71-a79e4a9a5e97-1727261840962-1727261852244]  ====================*/
BEGIN
BEGIN
  DECLARE tablesCount INT64;
  DECLARE tableNames ARRAY<STRING> DEFAULT ['\'WORKFLOW_7325e013be685ea0_3ead7e2085061473_result\''];
  EXECUTE IMMEDIATE '''
    SELECT COUNT(1) AS cnt
    FROM `cartodb-on-gcp-datascience.workflows_temp.__TABLES_SUMMARY__`
    WHERE table_id IN (''' || ARRAY_TO_STRING(tableNames, ', ') || ''')
  ''' INTO tablesCount;
  IF tablesCount < 1 THEN
    BEGIN
      BEGIN
      DECLARE tempInputTable STRING DEFAULT 'cartodb-on-gcp-datascience.workflows_temp.' || REPLACE(GENERATE_UUID(), '-', '_');
      DECLARE tempOutputTable STRING DEFAULT 'cartodb-on-gcp-datascience.workflows_temp.' || REPLACE(GENERATE_UUID(), '-', '_');
      DECLARE tempOutputTableKring STRING DEFAULT 'cartodb-on-gcp-datascience.workflows_temp.' || REPLACE(GENERATE_UUID(), '-', '_');
      DECLARE tempOutputTableKringRenamed STRING DEFAULT 'cartodb-on-gcp-datascience.workflows_temp.' || REPLACE(GENERATE_UUID(), '-', '_');
      EXECUTE IMMEDIATE
      REPLACE(
        '''CREATE TABLE IF NOT EXISTS `##tablename##`
        OPTIONS (
          expiration_timestamp = TIMESTAMP_ADD(
            CURRENT_TIMESTAMP(), INTERVAL 30 DAY
          )
        )
        AS
          SELECT * FROM `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_1372a306e980c44a_result`''',
        '##tablename##',
        tempInputTable
      );
      CALL `carto-un.carto`.ENRICH_GRID(
        'h3',
        tempInputTable,
        'h3',
        'SELECT * FROM `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_28ad301c26275c2e_result`',
        'geom',
        [('total_pop', 'sum'), ('median_age', 'avg'), ('median_rent', 'avg'), ('black_pop', 'sum'), ('hispanic_pop', 'sum'), ('owner_occupied_housing_units_median_value', 'sum'), ('vacant_housing_units', 'sum'), ('housing_units', 'sum'), ('families_with_young_children', 'sum')],
        [tempOutputTable]
      );
      
      EXECUTE IMMEDIATE
      REPLACE(
        '''CREATE TABLE IF NOT EXISTS `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_3ead7e2085061473_result`
        OPTIONS (
          expiration_timestamp = TIMESTAMP_ADD(
            CURRENT_TIMESTAMP(), INTERVAL 30 DAY
          )
        )
        AS
          SELECT * FROM `##tablename##`''',
        '##tablename##',
        tempOutputTable
      );
      END;
    END;
  END IF;
END;
END;

/*==================== native.h3enrich (v1) [17255adb-eb78-4fa7-9c71-a79e4a9a5e97-1727261840962]  ====================*/
BEGIN
BEGIN
  DECLARE tablesCount INT64;
  DECLARE tableNames ARRAY<STRING> DEFAULT ['\'WORKFLOW_7325e013be685ea0_60e15f68128b3d0b_result\''];
  EXECUTE IMMEDIATE '''
    SELECT COUNT(1) AS cnt
    FROM `cartodb-on-gcp-datascience.workflows_temp.__TABLES_SUMMARY__`
    WHERE table_id IN (''' || ARRAY_TO_STRING(tableNames, ', ') || ''')
  ''' INTO tablesCount;
  IF tablesCount < 1 THEN
    BEGIN
      BEGIN
      DECLARE tempInputTable STRING DEFAULT 'cartodb-on-gcp-datascience.workflows_temp.' || REPLACE(GENERATE_UUID(), '-', '_');
      DECLARE tempOutputTable STRING DEFAULT 'cartodb-on-gcp-datascience.workflows_temp.' || REPLACE(GENERATE_UUID(), '-', '_');
      DECLARE tempOutputTableKring STRING DEFAULT 'cartodb-on-gcp-datascience.workflows_temp.' || REPLACE(GENERATE_UUID(), '-', '_');
      DECLARE tempOutputTableKringRenamed STRING DEFAULT 'cartodb-on-gcp-datascience.workflows_temp.' || REPLACE(GENERATE_UUID(), '-', '_');
      EXECUTE IMMEDIATE
      REPLACE(
        '''CREATE TABLE IF NOT EXISTS `##tablename##`
        OPTIONS (
          expiration_timestamp = TIMESTAMP_ADD(
            CURRENT_TIMESTAMP(), INTERVAL 30 DAY
          )
        )
        AS
          SELECT * FROM `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_1372a306e980c44a_result`''',
        '##tablename##',
        tempInputTable
      );
      CALL `carto-un.carto`.ENRICH_GRID(
        'h3',
        tempInputTable,
        'h3',
        'SELECT * FROM `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_1fe0c48ce5671fe3_result`',
        'geom',
        [('total_pop', 'sum'), ('median_age', 'avg'), ('median_rent', 'avg'), ('black_pop', 'sum'), ('hispanic_pop', 'sum'), ('owner_occupied_housing_units_median_value', 'sum'), ('vacant_housing_units', 'sum'), ('housing_units', 'sum'), ('families_with_young_children', 'sum')],
        [tempOutputTable]
      );
      
      EXECUTE IMMEDIATE
      REPLACE(
        '''CREATE TABLE IF NOT EXISTS `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_60e15f68128b3d0b_result`
        OPTIONS (
          expiration_timestamp = TIMESTAMP_ADD(
            CURRENT_TIMESTAMP(), INTERVAL 30 DAY
          )
        )
        AS
          SELECT * FROM `##tablename##`''',
        '##tablename##',
        tempOutputTable
      );
      END;
    END;
  END IF;
END;
END;

/*==================== native.h3toparent (v1.0.0) [5a26dacc-aea0-46fa-a3e3-dbb3ea086682]  ====================*/
BEGIN
CREATE TABLE IF NOT EXISTS `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_b91702c61c0a174b_result`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(
    CURRENT_TIMESTAMP(), INTERVAL 30 DAY
  )
)
AS
  SELECT
    `carto-un.carto`.H3_TOPARENT(
      h3,
      7
    ) h3_parent,
    *
  FROM
    `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_23a9efda0ee5b354_result`;
END;

/*==================== native.h3enrich (v1) [17255adb-eb78-4fa7-9c71-a79e4a9a5e97-1725443583320-1725443612635-1727260591739]  ====================*/
BEGIN
BEGIN
  DECLARE tablesCount INT64;
  DECLARE tableNames ARRAY<STRING> DEFAULT ['\'WORKFLOW_7325e013be685ea0_eb3ca30fd68c190c_result\''];
  EXECUTE IMMEDIATE '''
    SELECT COUNT(1) AS cnt
    FROM `cartodb-on-gcp-datascience.workflows_temp.__TABLES_SUMMARY__`
    WHERE table_id IN (''' || ARRAY_TO_STRING(tableNames, ', ') || ''')
  ''' INTO tablesCount;
  IF tablesCount < 1 THEN
    BEGIN
      BEGIN
      DECLARE tempInputTable STRING DEFAULT 'cartodb-on-gcp-datascience.workflows_temp.' || REPLACE(GENERATE_UUID(), '-', '_');
      DECLARE tempOutputTable STRING DEFAULT 'cartodb-on-gcp-datascience.workflows_temp.' || REPLACE(GENERATE_UUID(), '-', '_');
      DECLARE tempOutputTableKring STRING DEFAULT 'cartodb-on-gcp-datascience.workflows_temp.' || REPLACE(GENERATE_UUID(), '-', '_');
      DECLARE tempOutputTableKringRenamed STRING DEFAULT 'cartodb-on-gcp-datascience.workflows_temp.' || REPLACE(GENERATE_UUID(), '-', '_');
      EXECUTE IMMEDIATE
      REPLACE(
        '''CREATE TABLE IF NOT EXISTS `##tablename##`
        OPTIONS (
          expiration_timestamp = TIMESTAMP_ADD(
            CURRENT_TIMESTAMP(), INTERVAL 30 DAY
          )
        )
        AS
          SELECT * FROM `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_1372a306e980c44a_result`''',
        '##tablename##',
        tempInputTable
      );
      CALL `carto-un.carto`.ENRICH_GRID(
        'h3',
        tempInputTable,
        'h3',
        'SELECT * FROM `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_5ec92f0643cdd666_result`',
        'geom',
        [('total_pop', 'sum'), ('median_age', 'avg'), ('median_rent', 'avg'), ('black_pop', 'sum'), ('hispanic_pop', 'sum'), ('owner_occupied_housing_units_median_value', 'sum'), ('vacant_housing_units', 'sum'), ('housing_units', 'sum'), ('families_with_young_children', 'sum')],
        [tempOutputTable]
      );
      
      EXECUTE IMMEDIATE
      REPLACE(
        '''CREATE TABLE IF NOT EXISTS `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_eb3ca30fd68c190c_result`
        OPTIONS (
          expiration_timestamp = TIMESTAMP_ADD(
            CURRENT_TIMESTAMP(), INTERVAL 30 DAY
          )
        )
        AS
          SELECT * FROM `##tablename##`''',
        '##tablename##',
        tempOutputTable
      );
      END;
    END;
  END IF;
END;
END;

/*==================== native.selectexpression (v1) [9d2ad7db-240a-40bc-a286-3f0bcfadcd64-1725444838451-1725444857695-1727260616633]  ====================*/
BEGIN
CREATE TABLE IF NOT EXISTS `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_2645f68905c397eb_result`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(
    CURRENT_TIMESTAMP(), INTERVAL 30 DAY
  )
)
AS
  SELECT *,
    2013 AS acs_year
  FROM `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_eb3ca30fd68c190c_result`;
END;

/*==================== native.selectexpression (v1) [9d2ad7db-240a-40bc-a286-3f0bcfadcd64]  ====================*/
BEGIN
CREATE TABLE IF NOT EXISTS `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_2d2cfe85bf79533d_result`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(
    CURRENT_TIMESTAMP(), INTERVAL 30 DAY
  )
)
AS
  SELECT *,
    2011 AS acs_year
  FROM `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_c63d6fe379d0a2b4_result`;
END;

/*==================== native.selectexpression (v1) [9d2ad7db-240a-40bc-a286-3f0bcfadcd64-1725444838451-1725444857695]  ====================*/
BEGIN
CREATE TABLE IF NOT EXISTS `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_6f68a118d6c3642e_result`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(
    CURRENT_TIMESTAMP(), INTERVAL 30 DAY
  )
)
AS
  SELECT *,
    2014 AS acs_year
  FROM `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_693de2260df94333_result`;
END;

/*==================== native.selectexpression (v1) [9d2ad7db-240a-40bc-a286-3f0bcfadcd64-1725444838451-1725444857695-1725444866674]  ====================*/
BEGIN
CREATE TABLE IF NOT EXISTS `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_8e62ffc22585c322_result`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(
    CURRENT_TIMESTAMP(), INTERVAL 30 DAY
  )
)
AS
  SELECT *,
    2019 AS acs_year
  FROM `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_3fa687a333388193_result`;
END;

/*==================== native.selectexpression (v1) [9d2ad7db-240a-40bc-a286-3f0bcfadcd64-1725444838451-1725444857695-1725444866674-1725444881420]  ====================*/
BEGIN
CREATE TABLE IF NOT EXISTS `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_9f775e56400dc1e3_result`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(
    CURRENT_TIMESTAMP(), INTERVAL 30 DAY
  )
)
AS
  SELECT *,
    2020 AS acs_year
  FROM `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_e1d810b6744d3f65_result`;
END;

/*==================== native.selectexpression (v1) [9d2ad7db-240a-40bc-a286-3f0bcfadcd64-1725444838451-1727261902944-1727261907138-1727261942595]  ====================*/
BEGIN
CREATE TABLE IF NOT EXISTS `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_6b441627cc611929_result`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(
    CURRENT_TIMESTAMP(), INTERVAL 30 DAY
  )
)
AS
  SELECT *,
    2012 AS acs_year
  FROM `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_a94a659360aa72b0_result`;
END;

/*==================== native.selectexpression (v1) [9d2ad7db-240a-40bc-a286-3f0bcfadcd64-1725444838451-1727261902944-1727261907138-1727261913833]  ====================*/
BEGIN
CREATE TABLE IF NOT EXISTS `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_d3ef282ecd563ce0_result`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(
    CURRENT_TIMESTAMP(), INTERVAL 30 DAY
  )
)
AS
  SELECT *,
    2010 AS acs_year
  FROM `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_23ae261785684c83_result`;
END;

/*==================== native.selectexpression (v1) [9d2ad7db-240a-40bc-a286-3f0bcfadcd64-1725444838451-1727261902944-1727261907138-1727261909653]  ====================*/
BEGIN
CREATE TABLE IF NOT EXISTS `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_a9e403ba5fc84f8c_result`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(
    CURRENT_TIMESTAMP(), INTERVAL 30 DAY
  )
)
AS
  SELECT *,
    2009 AS acs_year
  FROM `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_25e5d77258529f9b_result`;
END;

/*==================== native.selectexpression (v1) [9d2ad7db-240a-40bc-a286-3f0bcfadcd64-1725444838451-1727261902944-1727261907138]  ====================*/
BEGIN
CREATE TABLE IF NOT EXISTS `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_b19adbde85b0a568_result`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(
    CURRENT_TIMESTAMP(), INTERVAL 30 DAY
  )
)
AS
  SELECT *,
    2008 AS acs_year
  FROM `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_3ead7e2085061473_result`;
END;

/*==================== native.selectexpression (v1) [9d2ad7db-240a-40bc-a286-3f0bcfadcd64-1725444838451-1727261902944]  ====================*/
BEGIN
CREATE TABLE IF NOT EXISTS `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_87ddbcd2a41a92a5_result`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(
    CURRENT_TIMESTAMP(), INTERVAL 30 DAY
  )
)
AS
  SELECT *,
    2006 AS acs_year
  FROM `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_60e15f68128b3d0b_result`;
END;

/*==================== native.dropcolumn (v1) [8d89cdc0-8a02-4f86-a9f4-bf54dd57166b]  ====================*/
BEGIN
CREATE TABLE IF NOT EXISTS `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_e4be7c60fd5f790d_result`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(
    CURRENT_TIMESTAMP(), INTERVAL 30 DAY
  )
)
AS
  SELECT * EXCEPT (h3)
  FROM `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_b91702c61c0a174b_result`;
END;

/*==================== native.unionall (v1) [5623550f-32ba-49b3-bb40-bf2e77e6a2af]  ====================*/
BEGIN
CREATE TABLE IF NOT EXISTS `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_2ad9b33ec00a654c_result`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(
    CURRENT_TIMESTAMP(), INTERVAL 30 DAY
  )
)
AS
  SELECT * FROM `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_ccddd72e7cd672a6_result`
  UNION ALL
  SELECT * FROM `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_2d2cfe85bf79533d_result`
  UNION ALL
  SELECT * FROM `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_6f68a118d6c3642e_result`
  UNION ALL
  SELECT * FROM `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_8e62ffc22585c322_result`
  UNION ALL
  SELECT * FROM `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_9f775e56400dc1e3_result`
  UNION ALL
  SELECT * FROM `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_6b441627cc611929_result`
  UNION ALL
  SELECT * FROM `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_d3ef282ecd563ce0_result`
  UNION ALL
  SELECT * FROM `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_a9e403ba5fc84f8c_result`
  UNION ALL
  SELECT * FROM `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_b19adbde85b0a568_result`
  UNION ALL
  SELECT * FROM `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_87ddbcd2a41a92a5_result`;
END;

/*==================== native.renamecolumn (v1) [6361477b-7022-48df-acca-c6270b275bad]  ====================*/
BEGIN
CREATE TABLE IF NOT EXISTS `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_8a024409231b3364_result`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(
    CURRENT_TIMESTAMP(), INTERVAL 30 DAY
  )
)
AS
  SELECT * EXCEPT (h3_parent),
    h3_parent AS h3
  FROM `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_e4be7c60fd5f790d_result`;
END;

/*==================== native.groupby (v1) [ed07941e-444d-4247-86a1-980c84bea75b]  ====================*/
BEGIN
CREATE TABLE IF NOT EXISTS `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_1d465cab7b931e52_result`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(
    CURRENT_TIMESTAMP(), INTERVAL 30 DAY
  )
)
AS
  SELECT h3,
    ANY_VALUE(urbanity) urbanity_any
  FROM `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_8a024409231b3364_result`
  GROUP BY h3;
END;

/*==================== native.join (v1.2) [40931f09-96f6-4f00-a2b5-9a35143f8204]  ====================*/
BEGIN
DECLARE alias STRING;

EXECUTE IMMEDIATE
'''
  with __alias AS(
    SELECT CONCAT(
      '_joined.', column_name, ' AS ', column_name, '_joined'
    ) col_alias
    FROM `cartodb-on-gcp-datascience.workflows_temp`.INFORMATION_SCHEMA.COLUMNS
  WHERE table_name = 'WORKFLOW_7325e013be685ea0_1d465cab7b931e52_result'
  )
  SELECT STRING_AGG(col_alias, ', ')
  FROM __alias
'''
INTO alias;

EXECUTE IMMEDIATE
REPLACE(
  '''CREATE TABLE IF NOT EXISTS `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_9114a57e25505ce4_result`
  OPTIONS (
    expiration_timestamp = TIMESTAMP_ADD(
      CURRENT_TIMESTAMP(), INTERVAL 30 DAY
    )
  )
  AS
    SELECT
      _main.*,
      %s
    FROM
      `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_2ad9b33ec00a654c_result` AS _main
      INNER JOIN
      `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_1d465cab7b931e52_result` AS _joined
    ON
      _main.h3 = _joined.h3''',
  '%s',
  alias
);
END;

/*==================== native.dropcolumn (v1) [08b305b3-b245-4e49-913c-792ed605873f]  ====================*/
BEGIN
CREATE TABLE IF NOT EXISTS `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_12dc29eb47ce0cb2_result`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(
    CURRENT_TIMESTAMP(), INTERVAL 30 DAY
  )
)
AS
  SELECT * EXCEPT (h3_joined)
  FROM `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_9114a57e25505ce4_result`;
END;

/*==================== native.renamecolumn (v1) [79617090-4dc7-404e-b6cd-faab9988baf5]  ====================*/
BEGIN
CREATE TABLE IF NOT EXISTS `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_89ff105ddc222ec9_result`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(
    CURRENT_TIMESTAMP(), INTERVAL 30 DAY
  )
)
AS
  SELECT * EXCEPT (urbanity_any_joined),
    urbanity_any_joined AS urbanity_any
  FROM `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_12dc29eb47ce0cb2_result`;
END;

/*==================== native.saveastable (v1) [9de4e5f1-ce80-47a4-a346-40da24a98c79]  ====================*/
BEGIN
DROP TABLE IF EXISTS `cartobq.sdsc24_ny_workshops.CHI_boundary_enriched_w_ACS_2007_2020`;
CREATE TABLE IF NOT EXISTS `cartobq.sdsc24_ny_workshops.CHI_boundary_enriched_w_ACS_2007_2020`
AS
  SELECT * FROM `cartodb-on-gcp-datascience.workflows_temp.WORKFLOW_7325e013be685ea0_89ff105ddc222ec9_result`;
END;
